title: Easier Said than Done
description: Derailment of my side projects
author: Gavin Fynbo
github: https://github.com/gfynbo
about: A blog documenting, fixing, and building things for my various side projects that are all easier said than done. Most features and ideas sound easy in practice, but I often run into little things that sidetrack the whole process.
disqus_shortname: 
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/fynbo_gavin"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/gavin-fynbo"
    - icon: fa-github
      link: "https://github.com/gfynbo"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/

url: "https://gavinfynbo.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
